.THEME_NAME {
  .md-menu-content &.md-list {
    background-color: #{'BACKGROUND-COLOR'};
    color: #{'BACKGROUND-CONTRAST'};

    .md-menu-item {
      &:hover,
      &:focus,
      &.md-highlighted {
        .md-button:not([disabled]) {
          background-color: #{'BACKGROUND-CONTRAST-0.12'};
        }
      }

      &[disabled] {
        color: #{'BACKGROUND-CONTRAST-0.38'};
      }
    }
  }
}
