.THEME_NAME {
  .md-bottom-bar,
  &.md-bottom-bar {
    &:not(.md-shift) {
      .md-active {
        color: PRIMARY-COLOR;
      }
    }

    &.md-shift {
      background-color: PRIMARY-COLOR;
      color: PRIMARY-CONTRAST;

      &.md-accent {
        background-color: ACCENT-COLOR;
        color: ACCENT-CONTRAST;
      }

      &.md-warn {
        background-color: WARN-COLOR;
        color: WARN-CONTRAST;
      }
    }
  }
}
