sentimentBotToxicityThreshold: .7

sentimentBotReplyComment: >
  Please be sure to review the <a href="https://github.com/vuematerial/vue-material/blob/master/.github/CODE_OF_CONDUCT.md">Code of Conduct</a> and be respectful of other users. cc/ @marcosmoura

newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the <a href="https://github.com/vuematerial/vue-material/blob/master/.github/ISSUE_TEMPLATE.md">issue template</a>!

newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our <a href="https://github.com/vuematerial/vue-material/blob/master/.github/CONTRIBUTING.md">contributing</a> guidelines.

requestInfoReplyComment: >
  We would appreciate it if you could provide us with more info about this issue/pr!
