checks:
  file-lines:
    config:
      threshold: 300
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 40

ratings:
  paths:
    - build/**
    - docs/**
    - src/**
    - test/**

exclude_paths:
  - coverage/*
  - dist/*

plugins:
  eslint:
    enabled: false
    
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          patterns:
            - "src/**/*.js"
            - "src/**/*.vue"
            - "build/**/*.js"
            - "test/**/*.js"
            - "!src/**/*.test.js"

  markdownlint:
    enabled: true
    checks:
      MD002:
        enabled: false
      MD013:
        enabled: false
      MD038:
        enabled: false
      MD026:
        enabled: false
      MD033:
        enabled: false
      MD014:
        enabled: false

  fixme:
    enabled: true
    exclude_paths:
      - ".github/"
