.THEME_NAME {
  &.md-rating-bar {
    > .md-back-stars .md-icon {
      color: #{'BACKGROUND-CONTRAST-0.26'};
    }

    > .md-front-stars .md-icon {
      color: #{'BACKGROUND-CONTRAST-0.38'};
    }

    &.md-primary > .md-front-stars .md-icon {
      color: #{'PRIMARY-COLOR'};
    }

    &.md-accent > .md-front-stars .md-icon {
      color: #{'ACCENT-COLOR'};

    }

    &.md-warn > .md-front-stars .md-icon {
      color: #{'WARN-COLOR'};
    }
  }
}
