.THEME_NAME {
  &.md-table {

  }

  &.md-table-card {
    .md-toolbar {
      background-color: #{'BACKGROUND-COLOR'};
      color: #{'BACKGROUND-CONTRAST'};
    }
  }

  &.md-table-alternate-header {
    background-color: #{'BACKGROUND-COLOR'};

    .md-toolbar {
      background-color: #{'ACCENT-COLOR-A100-0.2'};
      color: #{'ACCENT-CONTRAST-A100'};
    }

    .md-counter {
      color: #{'ACCENT-COLOR'};
    }
  }
}
