.THEME_NAME {
  .md-input-container,
  &.md-input-container {
    &.md-input-focused {
      &.md-input-inline {
        label {
          color: rgba(#000, .54);
        }
      }

      &:after {
        height: 2px;
        background-color: PRIMARY-COLOR;
      }

      input {
        color: PRIMARY-COLOR;
        text-shadow: 0 0 0 BACKGROUND-CONTRAST;
        -webkit-text-fill-color: transparent;
      }

      label {
        color: PRIMARY-COLOR;
      }
    }
  }
}
