.THEME_NAME {
  &.md-toolbar {
    background-color: #{'PRIMARY-COLOR'};
    color: #{'PRIMARY-CONTRAST'};

    &.md-accent {
      background-color: #{'ACCENT-COLOR'};
      color: #{'ACCENT-CONTRAST'};
    }

    &.md-warn {
      background-color: #{'WARN-COLOR'};
      color: #{'WARN-CONTRAST'};
    }

    &.md-transparent {
      background-color: transparent;
      color: #{'BACKGROUND-CONTRAST'};
    }
  }
}
