.THEME_NAME {
  .md-checkbox,
  &.md-checkbox {
    &.md-checked {
      .md-checkbox-container {
        background-color: ACCENT-COLOR;
        border-color: ACCENT-COLOR;
      }

      .md-ink-ripple {
        color: ACCENT-COLOR;
      }

      .md-ripple {
        opacity: .38;
      }
    }

    &.md-disabled {
      .md-checkbox-container {
        border-color: transparent;
        background-color: rgba(#000, .26);
      }
    }
  }
}
