.THEME_NAME {
  .md-switch,
  &.md-switch {
    &.md-checked {
      .md-switch-container,
      .md-switch-thumb {
        background-color: ACCENT-COLOR;
      }

      .md-ink-ripple {
        color: ACCENT-COLOR;
      }

      .md-ripple {
        opacity: .38;
      }
    }

    &.md-disabled {
      .md-switch-container {
        background-color: rgba(#000, .12);
      }

      .md-switch-thumb {
        background-color: #bdbdbd;
      }
    }
  }
}
